name: Build with PyInstaller
on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Build
    runs-on: ${{ matrix.os }}-latest

    strategy:
      matrix:
        os: [ windows, macos ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller main.py

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ matrix.os }}
          path: dist/

  create_release:
    name: Create release
    runs-on: ubuntu-latest
    outputs:
      upload_url: ${{ steps.create_release.outputs.upload_url }}
    steps:
      - name: Create release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          draft: false
          prerelease: false

  upload_artifact:
    name: Upload artifact
    needs: [build, create_release]
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [ windows, macos ]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ matrix.os }}

      - name: Configure
        run: cp settings.json main/settings.json

      - name: Package
        run: zip -r ${{ matrix.os }}.zip main/

      - name: Upload asset
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ needs.create_release.outputs.upload_url }}
          asset_path: ./${{ matrix.os }}.zip
          asset_name: ${{ matrix.os }}.zip
          asset_content_type: application/zip
